### ISSUE TITLE
When import same module name in two package, it reports: `Attribute error occurs during compiling`

### ISSUE THREAD

**Issue by LeoLiuYan** [KusionStack/konfig#26]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

####  konfig/appops/guestbook-frontend/test/main.k
```
import base.pkg.kusion_models.test.frontend

appConfiguration: frontend.Server {
}
```

#### konfig/appops/guestbook-frontend/test/kcl.yaml
```
kcl_cli_configs:
  file:
    - main.k
    - ${KCL_MOD}/base/pkg/kusion_models/test/render/render.k
```

#### konfig/base/pkg/kusion_models/test/frontend/server.k
```
schema NewServer:
  a: str
```

#### konfig/base/pkg/kusion_models/test/render/render.k
```
import base.pkg.kusion_models.test.frontend as testFrontend
import base.pkg.kusion_models.kube.frontend


__renderTestServerInstances__ = [inst for inst in testFrontend.NewServer.instances()]
__renderServerFrontendInstances__ = [inst for inst in frontend.Server.instances() if typeof(inst) == "Server"]
```

### 2. What did you expect to see? (Required)

kusion compile success.

### 3. What did you see instead (Required)
```
3 |appConfiguration: frontend.NewServer {
                        19 ^  -> Failure
      module 'base.pkg.kusion_models.kube.frontend' has no attribute 'NewServer'
```

### 4. What is your KusionStack components version? (Required)

```
releaseVersion: v0.4.4
gitInfo:
    latestTag: v0.4.4
    commit: fd58099d9d38495eabd0dbf78f779c4f5cad0553
    treeState: clean
buildInfo:
    goVersion: go1.17.11
    GOOS: linux
    GOARCH: amd64
    numCPU: 2
    compiler: gc
    buildTime: "2022-06-24 08:40:18"
dependency:
    kclvmgoVersion: v0.4.2-alpha.9
    kclPluginVersion: v0.4.1-alpha2
```
