### ISSUE TITLE
The order of key-value pairs in compiled golden files is inconsistent with the compile result with current version kusion

### ISSUE THREAD

**Issue by amyXia1994** [KusionStack/konfig#71]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
cd appops/http-echo/dev
kusion compile
```

### 2. What did you expect to see? (Required)
nothing changed
### 3. What did you see instead (Required)
the `appops/http-echo/dev/ci-test/stdout.golden.yaml` file content changed
### 4. What is your KusionStack components version? (Required)
```
releaseVersion: v0.7.2
gitInfo:
    latestTag: v0.7.2
    commit: fb996130c1e4a8a30da7c04e672433ea6c870384
    treeState: clean
buildInfo:
    goVersion: go1.17.13
    GOOS: linux
    GOARCH: amd64
    numCPU: 2
    compiler: gc
    buildTime: "2022-12-02 07:00:28"
dependency:
    kclvmgoVersion: v0.4.4-alpha.1
    kclPluginVersion: v0.4.1-alpha2
```
