### ISSUE TITLE
app-service not found in http-echo demo

### ISSUE THREAD

**Issue by jakezhu9** [KusionStack/konfig#92]
### 1. Minimal reproduce step (Required)

```
cd appops/http-echo/dev/
kusion apply -y
kubectl describe ingress example-ingress -n http-echo
```

### 2. What did you expect to see? (Required)

ingress works as expected

### 3. What did you see instead (Required)

```
Name:             example-ingress
Labels:           <none>
Namespace:        http-echo
Address:          
Ingress Class:    nginx
Default backend:  <default>
Rules:
  Host        Path  Backends
  ----        ----  --------
  *           
              /apple   app-service:5678 (<error: endpoints "app-service" not found>)
Annotations:  <none>
```

### 4. What is your KusionStack components version? (Required)

```
releaseVersion: v0.7.1
gitInfo:
    latestTag: v0.7.1
    commit: 10eac925825c1bd087ad590d78670d3bcad6d5fd
    treeState: clean
buildInfo:
    goVersion: go1.17.13
    GOOS: linux
    GOARCH: amd64
    numCPU: 2
    compiler: gc
    buildTime: "2022-11-02 13:04:49"
dependency:
    kclvmgoVersion: v0.4.3
    kclPluginVersion: v0.4.1-alpha2
```
